remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: ${{ secret.GOOGLE_ANALYTICS_TAG }}
show_downloads: true
title: Data Engineering/Analytics
description: data engineering/analytics
